FROM php:7.3-fpm-stretch

RUN apt-get update
RUN apt-get install -y curl libxml2-dev zlib1g-dev libzip-dev

RUN curl --insecure https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer

COPY symfony.ini /usr/local/etc/php/conf.d/
ADD symfony.ini /etc/php7/php-fpm.d/
ADD symfony.ini /etc/php7/cli/conf.d/

COPY symfony.pool.conf /usr/local/etc/pool.d/

# Possible values for ext-name:
# bcmath bz2 calendar ctype curl dba dom enchant exif fileinfo filter ftp gd gettext gmp hash iconv imap interbase intl
# json ldap mbstring mcrypt mssql mysql mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci
# pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline recode reflection session shmop simplexml snmp soap
# sockets spl standard sybase_ct sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip

RUN docker-php-ext-configure iconv
RUN docker-php-ext-install iconv
RUN docker-php-ext-configure xml
RUN docker-php-ext-install xml
RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl
RUN docker-php-ext-configure zip
RUN docker-php-ext-install zip

RUN apt-get install -y mysql-client

# RUN apk add --no-cache freetype libpng libjpeg-turbo freetype-dev libpng-dev libjpeg-turbo-dev && \
#     docker-php-ext-configure gd \
#     --with-gd \
#     --with-freetype-dir=/usr/include/ \
#     --with-png-dir=/usr/include/ \
#     --with-jpeg-dir=/usr/include/ && \
#     NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) && \
#     docker-php-ext-install -j${NPROC} gd && \
#     apk del --no-cache freetype-dev libpng-dev libjpeg-turbo-dev

RUN docker-php-ext-install mbstring
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install opcache
RUN docker-php-ext-install soap
RUN docker-php-ext-install calendar

WORKDIR /var/www/symfony
EXPOSE 9001

RUN apt-get install -y python python-pip && pip install --upgrade awscli && mkdir -p /root/.aws/

RUN apt-get install -y gnupg
# RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt install -y nodejs
